# Generated by Django 4.1.3 on 2022-11-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='sobrenome',
            new_name='subtitulo',
        ),
    ]
